name: tch-py-3.11
channels:
  - conda-forge
dependencies:
  - python=3.11
  - filelock=3.15.4
  - Jinja2=3.1.4
  - MarkupSafe=2.1.5
  - mpmath=1.3.0
  - networkx=3.3
  - numpy=1.26.4
  - pillow=10.4.0
  - pip=24.0
  - setuptools=71.0.4
  - typing_extensions=4.12.2
  - wheel=0.43.0